### ISSUE TITLE
draftable-compare-api:1.2.1 has draftable:3-SNAPSHOT as parent

### ISSUE THREAD

**Issue by AbaGhenzi** [draftable/compare-api-java-client#2]
draftable-compare-api (version 1.2.1) has  draftable (version 3-SNAPSHOT) as parent.
https://repo1.maven.org/maven2/com/draftable/api/client/draftable-compare-api/1.2.1/draftable-compare-api-1.2.1.pom

I assume, the parent-version should be version 3.

Neither, version 3 or 3-SNAPSHOT, exists in maven.

https://mvnrepository.com/artifact/com.draftable.api.client/draftable

**Comment by ralish** [comment]
Hi @AbaGhenzi,

Sorry for the slow response. This issue appears to have been introduced by a change in our build system for Java artefacts. We're investigating it now and will provide a resolution as soon as possible.

**Comment by ralish** [comment]
Hi @AbaGhenzi,

We've fixed the problem internally and published a new release of the API client: v1.2.2. This correctly references a new version of the parent POM which has also been published. We've verified the artefacts are present in Maven Central. Apart from the fix to the parent POM version there are no other code changes.
